import ProjectDescription

let workspace = Workspace(name: "X-WingDial",
                          projects: ["."],
                          generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled))
